### ISSUE TITLE
CPU usage bottleneck

### ISSUE THREAD

**Issue by abreufilho** [TarunKumar1995-glitch/land_cover_classification_unet#1]
Congratulations for the code, it is being very useful to me right now! 

I am running the code locally on a i7-10700K CPU @ 3.80GHz × 16 (CPU) with 32 GB of RAM and a RTX 3060TI (GPU) and i am facing some spikes at huge CPU temperatures every time the model trains a new epoch.

Have you ran your models locally or at a Google Colab environment?

If it is local, which CUDA version you use?

**Comment by srimannarayanabaratam** [comment]
I used Colab on GPU runtime intially. But got fed up with the "timeouts" and setup a VM on GCP with k80. I am not sure if the spikes definitely correspond to the beginning of a new epoch and more specifically CPU. There isn't much going on after every epoch - even the model is saved based on the frequency you setup. If you're training on a large dataset, you might observe a different trend; you can let me know in this case.

**Comment by abreufilho** [comment]
I am training a model right now with the same dataset but cropped in 4x4 tiles of the original dataset. Each image had 2448x2448 and now they have 612x612.

So far it hasn't spiked CPU usage but has slowed down the process for each epoch, even with a batch size = 4.

When training time is over i'll post here if i got any spikes or high CPU temps again.

**Comment by abreufilho** [comment]
![image](https://user-images.githubusercontent.com/54593418/123864937-b0d6e480-d901-11eb-9566-f2399a740483.png)

Well, it is peaking to over 100% of CPU usage and whenever this happens my CPU temp goes above 80º.

Probably some configuration of my pytorch version or CUDA. Can't really investigate it for now.

As a workaround im running at a Google Colab environment so i dont explode my PC. Thank you anyway for the answers!
