### ISSUE TITLE
Using Model for Different Data Shape

### ISSUE THREAD

**Issue by gmvincent** [TarunKumar1995-glitch/land_cover_classification_unet#3]
I was wondering if this model/algorithm can be adapted to use a 9-channel hyperspectral image instead of an RGB image? Or can it be adapted to use an image with a 4D shaped tensor [time, height, width, channel (9)]?

**Comment by srimannarayanabaratam** [comment]
Hi there!

I am sure you can try more than 3 input cannels with UNet architecture.

However, for 4D tensors with time you might have to look at 3D
convolutions. An inflated version of 2D conv. Time dimension is unlike
geometrical dimension.

**Comment by gmvincent** [comment]
@TarunKumar1995-glitch, thank you!
